version: '3.8'

services:
  admin-backend:
    build:
      # build from repository root so 'shared/' and other sibling folders are included
      context: .
      dockerfile: admin-backend/Dockerfile.prod
    image: faq-admin-backend:latest
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FAQ_DATA_PATH=/app/python-bot/data
      - BOT_LOG_FILE=/app/python-bot/bot.log
      - DATABASE_URL=sqlite:./database.sqlite
    volumes:
      - ./admin-backend/database.sqlite:/app/database.sqlite
      - ./admin-backend/logs:/app/logs
    restart: unless-stopped

  admin-frontend:
    build:
      context: .
      dockerfile: admin-frontend/Dockerfile.prod
    image: faq-admin-frontend:latest
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3001
    depends_on:
      - admin-backend
    restart: unless-stopped

  python-bot:
    build:
      context: ./python-bot
      dockerfile: Dockerfile.prod
    image: faq-python-bot:latest
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=production
      - ADMIN_BACKEND_URL=http://admin-backend:3001
    volumes:
      - ./python-bot/data:/app/data
      - ./python-bot/logs:/app/logs
    depends_on:
      - admin-backend
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx_demo.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - admin-frontend
      - admin-backend
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
